FROM node:latest AS build-stage
WORKDIR /app
RUN npm install -g pnpm
COPY . .
RUN pnpm install
RUN pnpm run build
RUN ls -lah
FROM nginx:stable-alpine AS production-stage
# Copy the build application from the previous stage to the Nginx container
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy the nginx configuration file
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# Expose the port
EXPOSE 3000
# Allowing PWA to set title dynamically
COPY ./nginx/substitute_environment_variables_in_manifest.sh /docker-entrypoint.d/substitute_environment_variables_in_manifest.sh
RUN chmod +x /docker-entrypoint.d/substitute_environment_variables_in_manifest.sh
# Start Nginx to serve the application
CMD ["nginx", "-g", "daemon off;"]
