/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddExhibitorDialog: typeof import('./components/dialogs/AddExhibitorDialog.vue')['default']
    AddUserDialog: typeof import('./components/dialogs/AddUserDialog.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    EditDesign: typeof import('./components/EditDesign.vue')['default']
    ExhibitorCard: typeof import('./components/ExhibitorCard.vue')['default']
    ExhibitorOverview: typeof import('./components/ExhibitorOverview.vue')['default']
    ImportExhibitorsDialog: typeof import('./components/dialogs/ImportExhibitorsDialog.vue')['default']
    ListViewOfAccounts: typeof import('./components/ListViewOfAccounts.vue')['default']
    ListViewOfExhibitors: typeof import('./components/ListViewOfExhibitors.vue')['default']
    MoreInfoDialog: typeof import('./components/dialogs/MoreInfoDialog.vue')['default']
    PleaseWaitDialog: typeof import('./components/dialogs/PleaseWaitDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowInstallDialog: typeof import('./components/dialogs/ShowInstallDialog.vue')['default']
    WelcomeScreen: typeof import('./components/WelcomeScreen.vue')['default']
  }
}
