name: Create and publish Docker images

# Docker images should be build and pushed to registry on releases, new dev pushes and when triggered manually
on:
  release:
    types: [released, prereleased]
  push:
    branches:
      - 'dev'
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  
# We are building three images. Therefore, we use matrix.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Frontend
            image: ghcr.io/${{ github.repository }}Frontend
          - dockerfile: ./Backend
            image: ghcr.io/${{ github.repository }}Backend
          - dockerfile: .
            image: ghcr.io/${{ github.repository }}Webserver
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set RELEASE_TAG if release
        run: |
          if [[ "${{ github.event.release }}" != "" ]]; then
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi
      # Uses the `docker/login-action` action to log in to the Container registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=${{ env.RELEASE_TAG }},enable=${{ github.event.release != '' }}
            type=raw,value=latest,enable=${{ github.event.release != '' && !github.event.release.prerelease }}
            type=raw,value=prerelease,enable=${{ github.event.release != '' && github.event.release.prerelease }}
            type=raw,value={{branch}}-experimental,enable=${{ github.event_name == 'workflow_dispatch' }}
            type=raw,value={{branch}},enable=${{ github.event_name == 'push' }}
      # This step uses the `docker/build-push-action` action to build the image, based on the `Dockerfiles`. If the build succeeds, it pushes the image to GitHub Packages.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see [Usage](https://github.com/docker/build-push-action#usage) in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Frontend Docker image 
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ matrix.image}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
