name: Build Frontend

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10.27.0
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache-dependency-path: Frontend/pnpm-lock.yaml
          cache: pnpm
      - name: Install dependencies
        working-directory: ./Frontend
        run: pnpm install --frozen-lockfile
      - name: Lint
        working-directory: ./Frontend
        run: pnpm run lint
      - name: Build
        working-directory: ./Frontend
        run: pnpm run build
